"""listing

Revision ID: 6794b882fd5e
Revises: 
Create Date: 2025-06-21 11:11:02.762941

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision: str = '6794b882fd5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buy_usd', sa.Float(), nullable=False),
    sa.Column('sell_usd', sa.Float(), nullable=False),
    sa.Column('buy_eur', sa.Float(), nullable=False),
    sa.Column('sell_eur', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('profanity_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profanity_words_word'), 'profanity_words', ['word'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('car_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_models_id'), 'car_models', ['id'], unique=False)
    op.create_index(op.f('ix_car_models_name'), 'car_models', ['name'], unique=False)
    op.create_table('regions_or_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_or_states_id'), 'regions_or_states', ['id'], unique=False)
    op.create_index(op.f('ix_regions_or_states_name'), 'regions_or_states', ['name'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_expires_at', sa.Date(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_user_id'), 'users', ['auth_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions_or_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('car_model_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('original_currency', sa.Enum('UAH', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('price_uah', sa.Float(), nullable=True),
    sa.Column('image_urls', mysql.JSON(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text, nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dealership_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_models.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions_or_states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_index(op.f('ix_listings_car_model_id'), 'listings', ['car_model_id'], unique=False)
    op.create_index(op.f('ix_listings_country_id'), 'listings', ['country_id'], unique=False)
    op.create_index(op.f('ix_listings_region_id'), 'listings', ['region_id'], unique=False)
    op.create_index(op.f('ix_listings_city_id'), 'listings', ['city_id'], unique=False)
    op.create_index(op.f('ix_listings_price_uah'), 'listings', ['price_uah'], unique=False)
    op.create_table('listing_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_views_id'), 'listing_views', ['id'], unique=False)
    op.create_index(op.f('ix_listing_views_listing_id'), 'listing_views', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_views_viewed_at'), 'listing_views', ['viewed_at'], unique=False)

    # Define tables
    roles_table = table(
        'roles',
        column('id', sa.Integer),
        column('name', sa.String)
    )
    permissions_table = table(
        'permissions',
        column('id', sa.Integer),
        column('name', sa.String),
        column('description', sa.String)
    )
    role_permissions_table = table(
        'role_permissions',
        column('id', sa.Integer),
        column('role_id', sa.Integer),
        column('permission_id', sa.Integer)
    )
    brands_table = table(
        'brands',
        column('id', sa.Integer),
        column('name', sa.String)
    )
    car_models_table = table(
        'car_models',
        column('id', sa.Integer),
        column('name', sa.String),
        column('brand_id', sa.Integer)
    )
    countries_table = table(
        'countries',
        column('id', sa.Integer),
        column('name', sa.String)
    )
    regions_table = table(
        'regions_or_states',
        column('id', sa.Integer),
        column('name', sa.String),
        column('country_id', sa.Integer)
    )
    cities_table = table(
        'cities',
        column('id', sa.Integer),
        column('name', sa.String),
        column('region_id', sa.Integer)
    )
    profanity_words_table = table(
        'profanity_words',
        column('id', sa.Integer),
        column('word', sa.String)
    )

    # Adding seed data
    op.bulk_insert(
        roles_table,
        [
            {'name': 'admin'},
            {'name': 'manager'},
            {'name': 'user'}
        ]
    )
    op.bulk_insert(
        permissions_table,
        [
            {'name': 'manage_listings', 'description': 'Create/update/delete listings'},
            {'name': 'ban_user', 'description': None},
            {'name': 'changing_user_role', 'description': None},
            {'name': 'manage_roles_and_permissions', 'description': 'create/update/delete roles/permissions'},
            {'name': 'manage_role_permission_pair', 'description': 'create/delete role_permissions'},
            {'name': 'manage_profanity_words', 'description': 'add/delete profanity_words'},
            {'name': 'manage_cars', 'description': 'create/delete brands and models'},
            {'name': 'manage_regions', 'description': 'create/delete countries, regions and cities'},
            {'name': 'moderate_listings', 'description': 'moderate suspicious listings'},
        ]
    )
    op.bulk_insert(
        role_permissions_table,
        [
            {'role_id': 1, 'permission_id': 1},
            {'role_id': 1, 'permission_id': 2},
            {'role_id': 1, 'permission_id': 3},
            {'role_id': 1, 'permission_id': 4},
            {'role_id': 1, 'permission_id': 5},
            {'role_id': 1, 'permission_id': 6},
            {'role_id': 1, 'permission_id': 7},
            {'role_id': 1, 'permission_id': 8},
            {'role_id': 1, 'permission_id': 9},
            {'role_id': 2, 'permission_id': 2},
            {'role_id': 2, 'permission_id': 4},
            {'role_id': 2, 'permission_id': 6},
            {'role_id': 2, 'permission_id': 7},
            {'role_id': 2, 'permission_id': 8},
            {'role_id': 2, 'permission_id': 9},
            {'role_id': 3, 'permission_id': 1},
        ]
    )
    op.bulk_insert(
        brands_table,
        [
            {'name': 'Toyota'},
            {'name': 'BMW'},
            {'name': 'Honda'},
            {'name': 'Ford'},
            {'name': 'Nissan'},
            {'name': 'KIA'},
            {'name': 'AUDI'},
            {'name': 'Skoda'},
            {'name': 'Renault'},
            {'name': 'Opel'},
        ]
    )
    op.bulk_insert(
        car_models_table,
        [
            {'name': 'Corolla', 'brand_id': 1},
            {'name': 'RAV4', 'brand_id': 1},
            {'name': 'Camry', 'brand_id': 1},
            {'name': 'Hilux', 'brand_id': 1},
            {'name': 'Highlander', 'brand_id': 1},
            {'name': '3 Series', 'brand_id': 2},
            {'name': '5 Series', 'brand_id': 2},
            {'name': 'X5', 'brand_id': 2},
            {'name': 'X3', 'brand_id': 2},
            {'name': 'X1', 'brand_id': 2},
            {'name': 'CR-V', 'brand_id': 3},
            {'name': 'Civic', 'brand_id': 3},
            {'name': 'Accord', 'brand_id': 3},
            {'name': 'HR-V', 'brand_id': 3},
            {'name': 'Pilot', 'brand_id': 3},
            {'name': 'F-Series', 'brand_id': 4},
            {'name': 'Explorer', 'brand_id': 4},
            {'name': 'Ranger', 'brand_id': 4},
            {'name': 'Mustang', 'brand_id': 4},
            {'name': 'Escape', 'brand_id': 4},
            {'name': 'Qashqai', 'brand_id': 5},
            {'name': 'Altima', 'brand_id': 5},
            {'name': 'Sentra', 'brand_id': 5},
            {'name': 'X-Trail', 'brand_id': 5},
            {'name': 'Leaf', 'brand_id': 5},
            {'name': 'Sportage', 'brand_id': 6},
            {'name': 'Tucson', 'brand_id': 6},
            {'name': 'Seltos', 'brand_id': 6},
            {'name': 'Sorento', 'brand_id': 6},
            {'name': 'Rio', 'brand_id': 6},
            {'name': 'A3', 'brand_id': 7},
            {'name': 'A4', 'brand_id': 7},
            {'name': 'A6', 'brand_id': 7},
            {'name': 'Q5', 'brand_id': 7},
            {'name': 'Q7', 'brand_id': 7},
            {'name': 'Octavia', 'brand_id': 8},
            {'name': 'Fabia', 'brand_id': 8},
            {'name': 'Kodiaq', 'brand_id': 8},
            {'name': 'Superb', 'brand_id': 8},
            {'name': 'Karod', 'brand_id': 8},
            {'name': 'Clio', 'brand_id': 9},
            {'name': 'Captur', 'brand_id': 9},
            {'name': 'Megane', 'brand_id': 9},
            {'name': 'Duster', 'brand_id': 9},
            {'name': 'Kangoo', 'brand_id': 9},
            {'name': 'Corsa', 'brand_id': 10},
            {'name': 'Astra', 'brand_id': 10},
            {'name': 'Crossland', 'brand_id': 10},
            {'name': 'Grandland', 'brand_id': 10},
            {'name': 'Zafira', 'brand_id': 10},
        ]
    )
    op.bulk_insert(
        countries_table,
        [
            {'name': 'Ukraine'},
        ]
    )
    op.bulk_insert(
        regions_table,
        [
            {'name': 'Львівська', 'country_id': 1},
            {'name': 'Київська', 'country_id': 1},
            {'name': 'Миколаївська', 'country_id': 1},
            {'name': 'Одеська', 'country_id': 1},
            {'name': 'Вінницька', 'country_id': 1},
            {'name': 'Харківська', 'country_id': 1},
            {'name': 'Кіровоградська', 'country_id': 1},
        ]
    )
    op.bulk_insert(
        cities_table,
        [
            {'name': 'Львів', 'region_id': 1},
            {'name': 'Київ', 'region_id': 2},
            {'name': 'Миколаїв', 'region_id': 3},
            {'name': 'Одеса', 'region_id': 4},
            {'name': 'Вінниця', 'region_id': 5},
            {'name': 'Харків', 'region_id': 6},
            {'name': 'Кропивницький', 'region_id': 7},
        ]
    )
    op.bulk_insert(
        profanity_words_table,
        [
            {'word': 'погане'},
            {'word': 'Слово'},
            {'word': 'паршиве'},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_views_id'), table_name='listing_views')
    op.drop_table('listing_views')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_regions_or_states_id'), table_name='regions_or_states')
    op.drop_table('regions_or_states')
    op.drop_index(op.f('ix_car_models_name'), table_name='car_models')
    op.drop_index(op.f('ix_car_models_id'), table_name='car_models')
    op.drop_table('car_models')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_profanity_words_word'), table_name='profanity_words')
    op.drop_table('profanity_words')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
